:ems:
  :ems_workflows:
    :runner:
    :runner_options:
      :docker:
        :network: host
        :pull_policy: always
      :kubernetes:
        :pull_policy: Always
      :podman:
        :network: host
        :pull_policy: always
